package com.example.core.ai.gemini

import com.example.core.ai.AIResponseMessage
import com.example.core.ai.ConversationalAIService
import com.example.core.ai.GenerationPrompt
import com.example.core.config.AppConfig
import com.example.core.error.AppError
import com.example.core.result.AppResult
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import retrofit2.HttpException
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import java.io.IOException
import java.util.UUID
import java.util.concurrent.TimeUnit

class GeminiConversationalAIService(
  private val modelName: String = AppConfig.GEMINI_DEFAULT_MODEL,
  private val customApiKeyProvider: (() -> String)? = null,
) : ConversationalAIService {

  private val moshi: Moshi by lazy {
    Moshi.Builder()
      .add(KotlinJsonAdapterFactory())
      .build()
  }

  private val okHttpClient: OkHttpClient by lazy {
    OkHttpClient.Builder()
      .connectTimeout(60, TimeUnit.SECONDS)
      .readTimeout(60, TimeUnit.SECONDS)
      .writeTimeout(60, TimeUnit.SECONDS)
      .build()
  }

  private val apiService: GeminiApiService by lazy {
    Retrofit.Builder()
      .baseUrl(AppConfig.GEMINI_API_BASE_URL)
      .client(okHttpClient)
      .addConverterFactory(MoshiConverterFactory.create(moshi))
      .build()
      .create(GeminiApiService::class.java)
  }

  private fun resolveApiKey(): String {
    val key = customApiKeyProvider?.invoke() ?: AppConfig.getGeminiApiKey()
    return key.trim()
  }

  fun buildGeminiRequest(prompt: GenerationPrompt): GeminiGenerateContentRequest {
    val contentsList = mutableListOf<GeminiContent>()

    // Add prior conversation turns in sequence
    for (turn in prompt.history) {
      val mappedRole = if (turn.role.equals("model", ignoreCase = true) || turn.role.equals("assistant", ignoreCase = true)) {
        "model"
      } else {
        "user"
      }
      if (turn.text.isNotBlank()) {
        contentsList.add(
          GeminiContent(
            role = mappedRole,
            parts = listOf(GeminiPart(text = turn.text.trim())),
          )
        )
      }
    }

    // Add current user prompt
    contentsList.add(
      GeminiContent(
        role = "user",
        parts = listOf(GeminiPart(text = prompt.userPrompt.trim())),
      )
    )

    // System instruction
    val systemText = prompt.systemInstruction ?: AppConfig.KASA_SYSTEM_INSTRUCTION
    val systemInstructionContent = GeminiContent(
      parts = listOf(GeminiPart(text = systemText)),
    )

    return GeminiGenerateContentRequest(
      contents = contentsList,
      generationConfig = GeminiGenerationConfig(
        temperature = 0.7f,
        topP = 0.95f,
        topK = 40,
      ),
      systemInstruction = systemInstructionContent,
    )
  }

  override suspend fun generateResponse(
    userId: String,
    prompt: GenerationPrompt,
  ): AppResult<AIResponseMessage> = withContext(Dispatchers.IO) {
    val apiKey = resolveApiKey()
    if (apiKey.isBlank()) {
      return@withContext AppResult.Error(
        AppError.AiEngineError("Gemini API key is not configured. Please set GEMINI_API_KEY in Secrets.")
      )
    }

    try {
      val request = buildGeminiRequest(prompt)
      val response = apiService.generateContent(
        model = modelName,
        apiKey = apiKey,
        request = request,
      )

      val candidate = response.candidates?.firstOrNull()
      val text = candidate?.content?.parts?.firstOrNull()?.text
      if (text.isNullOrBlank()) {
        return@withContext AppResult.Error(
          AppError.AiEngineError("No response was generated by the AI model.")
        )
      }

      val responseMessage = AIResponseMessage(
        id = "ai_" + UUID.randomUUID().toString().take(8),
        content = text.trim(),
        timestamp = System.currentTimeMillis(),
        finishReason = candidate.finishReason,
      )
      AppResult.Success(responseMessage)
    } catch (e: HttpException) {
      val errorMsg = when (e.code()) {
        400 -> "Invalid AI request parameters (HTTP 400)."
        401, 403 -> "Authentication error with Gemini API (HTTP ${e.code()}). Check your API Key."
        429 -> "Rate limit reached for Gemini API. Please wait a moment and retry."
        500, 503 -> "Gemini API server temporarily unavailable (HTTP ${e.code()}). Please retry."
        else -> "AI service communication error (HTTP ${e.code()})."
      }
      AppResult.Error(AppError.AiEngineError(errorMsg, cause = e))
    } catch (e: IOException) {
      AppResult.Error(
        AppError.NetworkError("Network connection error. Please check your internet connection.", cause = e)
      )
    } catch (e: Exception) {
      AppResult.Error(
        AppError.AiEngineError(e.localizedMessage ?: "Unexpected error during AI generation.", cause = e)
      )
    }
  }

  override fun streamResponse(
    userId: String,
    prompt: GenerationPrompt,
  ): Flow<AppResult<String>> = flow {
    val apiKey = resolveApiKey()
    if (apiKey.isBlank()) {
      emit(AppResult.Error(AppError.AiEngineError("Gemini API key is not configured. Please set GEMINI_API_KEY in Secrets.")))
      return@flow
    }

    try {
      val request = buildGeminiRequest(prompt)
      val responseBody = apiService.generateContentStream(
        model = modelName,
        apiKey = apiKey,
        alt = "sse",
        request = request,
      )

      val adapter = moshi.adapter(GeminiGenerateContentResponse::class.java)
      val fullAccumulator = StringBuilder()

      responseBody.byteStream().bufferedReader().use { reader ->
        var line: String?
        while (reader.readLine().also { line = it } != null) {
          val currentLine = line ?: continue
          if (currentLine.startsWith("data:")) {
            val jsonPayload = currentLine.removePrefix("data:").trim()
            if (jsonPayload.isNotEmpty() && jsonPayload != "[DONE]") {
              try {
                val parsed = adapter.fromJson(jsonPayload)
                val partText = parsed?.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                if (!partText.isNullOrEmpty()) {
                  fullAccumulator.append(partText)
                  emit(AppResult.Success(partText))
                }
              } catch (ignored: Exception) {
                // Ignore parse errors on partial SSE control frames
              }
            }
          }
        }
      }

      if (fullAccumulator.isEmpty()) {
        // Fallback: if SSE stream had no chunks, try non-streaming fallback
        val single = generateResponse(userId, prompt)
        when (single) {
          is AppResult.Success -> emit(AppResult.Success(single.data.content))
          is AppResult.Error -> emit(AppResult.Error(single.error))
          is AppResult.Loading -> Unit
        }
      }
    } catch (e: HttpException) {
      val errorMsg = when (e.code()) {
        400 -> "Invalid AI request parameters (HTTP 400)."
        401, 403 -> "Authentication error with Gemini API (HTTP ${e.code()}). Check your API Key."
        429 -> "Rate limit reached for Gemini API. Please wait a moment."
        500, 503 -> "Gemini API server temporarily unavailable (HTTP ${e.code()})."
        else -> "AI service communication error (HTTP ${e.code()})."
      }
      emit(AppResult.Error(AppError.AiEngineError(errorMsg, cause = e)))
    } catch (e: IOException) {
      emit(AppResult.Error(AppError.NetworkError("Network connection error. Check your internet connection.", cause = e)))
    } catch (e: Exception) {
      emit(AppResult.Error(AppError.AiEngineError(e.localizedMessage ?: "Unexpected streaming error.", cause = e)))
    }
  }.flowOn(Dispatchers.IO)
}
